# docker-compose.yml
version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres-local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: koyebdb
      POSTGRES_USER: koyeb-adm
      POSTGRES_PASSWORD: npg_qifZo51xQMkI
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
