male_names = [
    "José",
    "Juan",
    "Luis",
    "Carlos",
    "Jesús",
    "Manuel",
    "Miguel",
    "Pedro",
    "Francisco",
    "Jorge",
    "Antonio",
    "Alejandro",
    "Daniel",
    "Fernando",
    "Roberto",
    "Ricardo",
    "Eduardo",
    "David",
    "Rafael",
    "Arturo",
    "Javier",
    "Raúl",
    "Sergio",
    "Alberto",
    "Rubén",
    "Enrique",
    "Gerardo",
    "Guillermo",
    "Alfredo",
    "Armando",
    "Gabriel",
    "Andrés",
    "Mario",
    "Óscar",
    "Pablo",
    "Rodrigo",
    "Felipe",
    "Jaime",
    "Ignacio",
    "Salvador",
    "Víctor",
    "Emilio",
    "Ernesto",
    "Adrián",
    "César",
    "Martín",
    "Esteban",
    "Diego",
    "Samuel",
    "Ramón",
    "Héctor",
    "Julio",
    "Alfonso",
    "Joaquín",
    "Hugo",
    "Leonardo",
    "Gilberto",
    "Isaac",
    "Gustavo",
    "Omar",
    "Erick",
    "Israel",
    "Ángel",
    "Saúl",
    "Oliver",
    "Rodolfo",
    "Marcos",
    "Efraín",
    "Bernardo",
    "Benito",
    "Ramiro",
    "Federico",
    "Agustín",
    "Baltazar",
    "René",
    "Octavio",
    "Ulises",
    "Patricio",
    "Noé",
    "Maximiliano",
    "Gregorio",
    "Tomás",
    "Lorenzo",
    "Simón",
    "Mateo",
    "Adolfo",
    "Abel",
    "Emanuel",
    "Nicolás",
    "Edgar",
    "Alan",
    "Aarón",
    "Damián",
    "Elián",
    "Elías",
    "Fabián",
    "Fermín",
    "Flavio",
    "Gaspar",
    "Gonzalo",
    "Heriberto",
    "Homero",
    "Horacio",
    "Iker",
    "Ismael",
    "Ivan",
    "Jacobo",
    "Jairo",
    "Jaziel",
    "Jerónimo",
    "Jonás",
    "Josué",
    "Leobardo",
    "Luciano",
    "Marcelo",
    "Mariano",
    "Mauro",
    "Misael",
    "Néstor",
    "Norberto",
    "Orlando",
    "Osvaldo",
    "Pascual",
    "Quirino",
    "Reyes",
    "Rigoberto",
    "Rogelio",
    "Roque",
    "Sabas",
    "Severiano",
    "Tadeo",
    "Teodoro",
    "Timoteo",
    "Valentín",
    "Vicente",
    "Yael",
    "Zacarías",
    "Aarón",
    "Abelardo",
    "Adalberto",
    "Adán",
    "Adelmo",
    "Agustín",
    "Aldo",
    "Alexis",
    "Alonso",
    "Amado",
    "Amador",
    "Ambrocio",
    "Anastasio",
    "Andrés",
    "Aníbal",
    "Anselmo",
    "Apolinar",
    "Apolonio",
    "Aquiles",
    "Arcadio",
    "Ariel",
    "Arsenio",
    "Artemio",
    "Asael",
    "Aurelio",
    "Baltasar",
    "Bartolomé",
    "Basilio",
    "Baudelio",
    "Belisario",
    "Benedicto",
    "Benigno",
    "Benjamín",
    "Bernabé",
    "Bonifacio",
    "Braulio",
    "Buenaventura",
    "Cándido",
    "Casimiro",
    "Celestino",
    "Celso",
    "Cipriano",
    "Cirilo",
    "Claudio",
    "Cleto",
    "Conrado",
    "Cornelio",
    "Crispín",
    "Cristián",
    "Cristóbal",
    "Dacio",
    "Dámaso",
    "Darío",
    "Delio",
    "Demetrio",
    "Desiderio",
    "Dionisio",
    "Donato",
    "Doroteo",
    "Edelmiro",
    "Edmundo",
    "Eduvigis",
    "Eleuterio",
    "Eliseo",
    "Eloy",
    "Emerico",
    "Epifanio",
    "Erasmo",
    "Erico",
    "Eulalio",
    "Eusebio",
    "Eutimio",
    "Evaristo",
    "Everardo",
    "Exequiel",
    "Ezequiel",
    "Fabricio",
    "Faustino",
    "Feliciano",
    "Fidel",
    "Filemón",
    "Florentino",
    "Fortunato",
    "Franco",
    "Galdino",
    "Gamaliel",
    "Geraldo",
    "Germán",
    "Gervasio",
    "Godofredo",
    "Gualberto",
    "Guido",
    "Guillén",
    "Gumersindo",
    "Heliodoro",
    "Heraclio",
    "Hermenegildo",
    "Hernán",
    "Hilario",
    "Hipólito",
    "Honorio",
    "Ifigenio",
    "Inocencio",
    "Irineo",
    "Isidoro",
    "Isidro",
    "Jacinto",
    "Jenaro",
    "Jeremías",
    "Jordi",
    "Josafat",
    "Jovito",
    "Juvenal",
    "Ladislao",
    "Laureano",
    "Lauro",
    "Leandro",
    "Leocadio",
    "León",
    "Leopoldo",
    "Liborio",
    "Lino",
    "Lisandro",
    "Lope",
    "Lucas",
    "Lucio",
    "Macario",
    "Magín",
    "Marcial",
    "Marino",
    "Matías",
    "Mauricio",
    "Melchor",
    "Melquíades",
    "Modesto",
    "Nabor",
    "Narciso",
    "Natalio",
    "Nazario",
    "Nicandro",
    "Nicodemo",
    "Nicanor",
    "Olegario",
    "Onésimo",
    "Orestes",
    "Oseas",
    "Otilio",
    "Pánfilo",
    "Pascual",
    "Paulino",
    "Plácido",
    "Poncio",
    "Porfirio",
    "Primitivo",
    "Prospero",
    "Prudencio",
    "Raimundo",
    "Refugio",
    "Reinaldo",
    "Remigio",
    "Renato",
    "Rito",
    "Rolando",
    "Rosendo",
    "Rufino",
    "Ruperto",
    "Salomón",
    "Sansón",
    "Santos",
    "Saturnino",
    "Segismundo",
    "Silvestre",
    "Simeón",
    "Tarsicio",
    "Telmo",
    "Teófilo",
    "James",
    "Robert",
    "John",
    "Michael",
    "David",
    "William",
    "Richard",
    "Joseph",
    "Thomas",
    "Christopher",
    "Daniel",
    "Matthew",
    "Anthony",
    "Mark",
    "Donald",
    "Steven",
    "Paul",
    "Andrew",
    "Joshua",
    "Kenneth",
    "Kevin",
    "Brian",
    "George",
    "Edward",
    "Ronald",
    "Timothy",
    "Jason",
    "Jeffrey",
    "Ryan",
    "Jacob",
    "Gary",
    "Nicholas",
    "Eric",
    "Jonathan",
    "Stephen",
    "Larry",
    "Justin",
    "Scott",
    "Brandon",
    "Benjamin",
    "Samuel",
    "Frank",
    "Gregory",
    "Raymond",
    "Alexander",
    "Patrick",
    "Jack",
    "Dennis",
    "Jerry",
    "Tyler",
    "Aaron",
    "Jose",
    "Henry",
    "Douglas",
    "Adam",
    "Peter",
    "Nathan",
    "Zachary",
    "Walter",
    "Kyle",
    "Harold",
    "Carl",
    "Jeremy",
    "Keith",
    "Roger",
    "Gerald",
    "Ethan",
    "Arthur",
    "Terry",
    "Christian",
    "Sean",
    "Lawrence",
    "Austin",
    "Joe",
    "Noah",
    "Jesse",
    "Albert",
    "Bryan",
    "Billy",
    "Bruce",
    "Jordan",
    "Ralph",
    "Roy",
    "Eugene",
    "Wayne",
    "Alan",
    "Juan",
    "Louis",
    "Russell",
    "Gabriel",
    "Randy",
    "Philip",
    "Harry",
    "Dylan",
    "Vincent",
    "Logan",
    "Bobby",
    "Johnny",
    "Clifford",
    "Howard",
    "Leonard",
    "Caleb",
    "Martin",
    "Jimmy",
    "Ernest",
    "Glenn",
    "Fred",
    "Tiburcio",
    "Tito",
    "Toribio",
    "Trinidad",
    "Ubaldo",
    "Uriel",
    "Urbano",
    "Valero",
    "Venancio",
    "Víctor",
    "Vidal",
    "Viriato",
    "Vitalicio",
    "Wilfrido",
    "Xavier",
    "Yago",
    "Zaqueo",
    "Zeferino",
    "Zenón",
]

female_names = [
    "María",
    "Guadalupe",
    "Juana",
    "Margarita",
    "Josefina",
    "Verónica",
    "Leticia",
    "Ana",
    "Luisa",
    "Carmen",
    "Rosa",
    "Teresa",
    "Patricia",
    "Elizabeth",
    "Claudia",
    "Dolores",
    "Alejandra",
    "Silvia",
    "Yolanda",
    "Gabriela",
    "Laura",
    "María Fernanda",
    "María José",
    "Sofía",
    "Valeria",
    "Ximena",
    "Camila",
    "Daniela",
    "Mariana",
    "Fernanda",
    "Regina",
    "Victoria",
    "Paulina",
    "Adriana",
    "Beatriz",
    "Lucía",
    "Irma",
    "Alma",
    "Elena",
    "Blanca",
    "Esmeralda",
    "Olivia",
    "Mayra",
    "Karla",
    "Brenda",
    "Nancy",
    "Alicia",
    "Rocío",
    "Gloria",
    "Erika",
    "Marisol",
    "Karina",
    "Liliana",
    "Catalina",
    "Jimena",
    "Pilar",
    "Consuelo",
    "Esther",
    "Miriam",
    "Perla",
    "Susana",
    "Fabiola",
    "Janet",
    "Norma",
    "Raquel",
    "Rebeca",
    "Ángela",
    "Eva",
    "Salma",
    "Wendy",
    "Zoe",
    "Ingrid",
    "Maribel",
    "Lourdes",
    "Cecilia",
    "Luz",
    "Concepción",
    "Magdalena",
    "Mercedes",
    "Julia",
    "Rosario",
    "Amalia",
    "Antonia",
    "Carolina",
    "Delia",
    "Estela",
    "Fátima",
    "Graciela",
    "Isabel",
    "Jessica",
    "Karen",
    "Marcela",
    "Natalia",
    "Ofelia",
    "Pamela",
    "Ruth",
    "Sara",
    "Vanessa",
    "Yaretzi",
    "Abigail",
    "Berenice",
    "Cristina",
    "Diana",
    "Elsa",
    "Flor",
    "Giselle",
    "Hilda",
    "Ivette",
    "Jazmín",
    "Kenia",
    "Lilia",
    "Mónica",
    "Nadia",
    "Olga",
    "Quetzalli",
    "Renata",
    "Sabrina",
    "Tania",
    "Úrsula",
    "Viviana",
    "Xóchitl",
    "Yessica",
    "Zulema",
    "Abril",
    "Aída",
    "América",
    "Anahí",
    "Ángeles",
    "Araceli",
    "Azucena",
    "Belén",
    "Brissa",
    "Candelaria",
    "Clara",
    "Dafne",
    "Edith",
    "Elisa",
    "Emilia",
    "Erendira",
    "Francisca",
    "Georgina",
    "Helena",
    "Irene",
    "Jacqueline",
    "Jovita",
    "Krystal",
    "Leonor",
    "Lizbeth",
    "Martha",
    "Naomi",
    "Oralia",
    "Petra",
    "Ramona",
    "Rosalba",
    "Sandra",
    "Tamara",
    "Violeta",
    "Xiomara",
    "Yuridia",
    "Zaida",
    "Alondra",
    "Anabel",
    "Aurora",
    "Bernarda",
    "Celeste",
    "Denisse",
    "Elvia",
    "Eugenia",
    "Frida",
    "Guillermina",
    "Haydee",
    "Ilse",
    "Jocelyn",
    "Julieta",
    "Kimberly",
    "Lorena",
    "Marcelina",
    "Nelly",
    "Odalys",
    "Priscila",
    "Rubí",
    "Selene",
    "Tatiana",
    "Ursula",
    "Valentina",
    "Yazmín",
    "Zenia",
    "Adela",
    "Agustina",
    "Alejandrina",
    "Amada",
    "Anayeli",
    "Arlette",
    "Barbara",
    "Betsabé",
    "Casandra",
    "Citlalli",
    "Dalila",
    "Elia",
    "Eunice",
    "Felicitas",
    "Genoveva",
    "Herlinda",
    "Imelda",
    "Jackeline",
    "Kassandra",
    "Layla",
    "Leticia",
    "Maricela",
    "Nayeli",
    "Odalis",
    "Pauline",
    "Querida",
    "Rosalía",
    "Sanjuana",
    "Teresita",
    "Urbana",
    "Vanesa",
    "Wendolin",
    "Xenia",
    "Yolotzin",
    "Zaira",
    "Amaranta",
    "Annette",
    "Apolonia",
    "Arely",
    "Atzimba",
    "Briseida",
    "Calista",
    "Corina",
    "Dulce",
    "Elaine",
    "Esperanza",
    "Filomena",
    "Geraldine",
    "Harumi",
    "Ixchel",
    "Josefa",
    "Keyla",
    "Lidia",
    "María Guadalupe",
    "María del Carmen",
    "María Elena",
    "María Isabel",
    "María Luisa",
    "María Teresa",
    "María de Jesús",
    "Mireya",
    "Nereida",
    "Oriana",
    "Pilar",
    "Rosaura",
    "Silvana",
    "Tlalli",
    "Vianey",
    "Yara",
    "Zindy",
    "Aleida",
    "Anel",
    "Aurelia",
    "Bárbara",
    "Claudette",
    "Danna",
    "Elvira",
    "Estrella",
    "Florinda",
    "Griselda",
    "Hortensia",
    "Itzel",
    "Johana",
    "Lilian",
    "Marissa",
    "Nitzia",
    "Olimpia",
    "Paloma",
    "Reyna",
    "Soledad",
    "Trinidad",
    "Velia",
    "Yadira",
    "Zoe",
]

domains = [
    "@gmail.com",
    "@hotmail.com",
    "@outlook.com",
    "@yahoo.com.mx",
    "@yahoo.com",
    "@live.com.mx",
    "@live.com",
    "@prodigy.net.mx",
    "@unam.mx",
    "@itesm.mx",
    "@tec.mx",
    "@ipn.mx",
    "@empresarial.com",
    "@aol.com",
    "@icloud.com",
    "@mail.com",
    "@zoho.com",
    "@mxmail.com",
    "@uabc.edu.mx",
    "@udg.mx",
    "@uv.mx",
    "@empresa.com.mx",
    "@consultores.com",
]

habits_by_category = {
    "ENERGIA": [
        (
            "Apagar luces innecesarias",
            "Apaga las luces cuando salgas de una habitación.",
        ),
        (
            "Desconectar aparatos",
            "Desconecta cargadores y electrodomésticos que no uses.",
        ),
        ("Usar focos LED", "Reemplaza bombillas por opciones más eficientes."),
        (
            "Usar electrodomésticos eficientes (A+++)",
            "Prioriza dispositivos con certificación energética A+++.",
        ),
        (
            "Aprovechar la luz natural",
            "Usa ventanas y cortinas claras para reducir necesidad de luz artificial.",
        ),
        (
            "Configurar termostato inteligente",
            "Mantén 20°C en invierno y 25°C en verano para ahorrar energía.",
        ),
        ("Secar ropa al sol", "Evita la secadora eléctrica siempre que sea posible."),
        ("Instalar paneles solares", "Genera energía renovable en casa si es viable."),
        (
            "Usar modos eco en electrodomésticos",
            "Lava ropa o platos con programas de bajo consumo.",
        ),
        (
            "Ventilar la casa eficientemente",
            "Abre ventanas solo 10 min para renovar aire sin perder calor/frío.",
        ),
        (
            "Cocinar con ollas a presión",
            "Reduce tiempo y energía al preparar alimentos.",
        ),
        (
            "Evitar abrir el horno innecesariamente",
            "Cada apertura pierde un 20% de calor acumulado.",
        ),
        (
            "Usar ventiladores en lugar de aire acondicionado",
            "Consumen hasta un 90% menos de energía.",
        ),
        (
            "Desenchufar dispositivos en standby",
            "El 'consumo fantasma' puede llegar al 10% de tu factura.",
        ),
        ("Calentar agua con energía solar", "Instala un calentador solar para duchas."),
        (
            "Agrupar comidas al horno",
            "Aprovecha el calor residual para cocinar varios platos.",
        ),
        (
            "Usar laptops en lugar de PCs de escritorio",
            "Consumen hasta un 50% menos de energía.",
        ),
        (
            "Pintar paredes de colores claros",
            "Reflejan mejor la luz y reducen necesidad de iluminación.",
        ),
        (
            "Instalar toldos o persianas en verano",
            "Disminuyen la necesidad de aire acondicionado.",
        ),
        (
            "Programar apagado automático de dispositivos",
            "Configura tu computadora o TV para que se apaguen solos.",
        ),
        ("Limpiar focos y lámparas", "Mejora la eficiencia de la iluminación."),
        (
            "Instalar detectores de movimiento",
            "Evita luces encendidas innecesariamente.",
        ),
        ("Bajar brillo de pantallas", "Reduce consumo energético en dispositivos."),
        ("Apagar modem/router por la noche", "Ahorra energía mientras duermes."),
        (
            "Usar microondas en lugar de horno",
            "Consume menos energía para pequeñas porciones.",
        ),
        (
            "Desactivar funciones automáticas",
            "Reduce uso innecesario de energía en TVs u otros.",
        ),
        (
            "Realizar mantenimiento de electrodomésticos",
            "Asegura funcionamiento eficiente.",
        ),
        ("Usar cortinas térmicas", "Aíslan y reducen uso de calefacción o aire."),
        (
            "Lavar ropa con agua fría",
            "Evita consumo energético por calentamiento de agua.",
        ),
        ("Evitar el uso de secadora", "Prefiere el secado al aire libre."),
    ],
    "AGUA": [
        ("Ducha rápida (5 min)", "Reduce tu tiempo en la ducha para ahorrar agua."),
        ("Cerrar llave al cepillar dientes", "Ahorra hasta 12 litros por minuto."),
        ("Reutilizar agua de lluvia", "Recolecta agua para regar plantas o limpieza."),
        (
            "Usar lavadora y lavavajillas con carga completa",
            "Optimiza cada ciclo de lavado.",
        ),
        ("Reparar fugas inmediatamente", "Una gotera puede perder 30 litros diarios."),
        ("Regar plantas al amanecer o atardecer", "Evita la evaporación por el sol."),
        ("Instalar grifos con aireador", "Reducen el caudal sin perder presión."),
        (
            "Usar balde en lugar de manguera para lavar autos",
            "Ahorra hasta 300 litros por lavada.",
        ),
        ("No descongelar alimentos bajo el grifo", "Usa el refrigerador o microondas."),
        (
            "Recoger agua fría de la ducha mientras esperas la caliente",
            "Úsala para plantas o limpieza.",
        ),
        (
            "Instalar inodoros de doble descarga",
            "Permiten usar solo el agua necesaria.",
        ),
        ("Lavar frutas/verduras en un recipiente", "No bajo el grifo abierto."),
        (
            "Usar escoba en lugar de manguera para limpiar patios",
            "Ahorra miles de litros al año.",
        ),
        ("Elegir plantas autóctonas en jardines", "Requieren menos riego."),
        (
            "No usar el inodoro como basurera",
            "Cada descarga innecesaria gasta 6-12 litros.",
        ),
        (
            "Usar sistemas de riego por goteo",
            "Son un 50% más eficientes que el riego tradicional.",
        ),
        ("Reutilizar agua de cocción", "Por ejemplo, para regar o hacer sopas."),
        ("Limpiar aceras con barredera en lugar de agua", "Prioriza métodos secos."),
        ("Usar cubetas para lavar ropa a mano", "Gasta menos que el grifo abierto."),
        ("Educar a niños en el ahorro de agua", "Fomenta hábitos desde pequeños."),
        ("Recolectar agua del aire acondicionado", "Úsala para regar o limpiar."),
        ("Instalar sensores de humedad en jardines", "Evitan el riego innecesario."),
        ("Cerrar llave al enjabonar platos", "Solo abrir al enjuagar."),
        ("Ducharse con música de 5 min", "Termina la ducha al acabar la canción."),
        ("Detectar fugas con el medidor", "Verifica si hay consumo sin uso visible."),
        ("Usar lavadora en modo ecológico", "Reduce consumo de agua y energía."),
        ("Elegir ropa que se ensucie menos", "Evita lavados frecuentes innecesarios."),
        ("Descongelar alimentos al ambiente", "Evita uso de agua."),
        ("Barrer antes de trapear", "Evita necesidad de cambiar el agua varias veces."),
        (
            "Cerrar la llave entre pasos de limpieza",
            "Ej. al trapear o limpiar ventanas.",
        ),
    ],
    "RESIDUOS": [
        (
            "Separar residuos (orgánico, reciclable, basura)",
            "Facilita el reciclaje y compostaje.",
        ),
        ("Compostar desechos orgánicos", "Crea abono natural para plantas."),
        (
            "Evitar plásticos de un solo uso",
            "Usa bolsas de tela y recipientes reutilizables.",
        ),
        (
            "Reciclar electrónicos en puntos autorizados",
            "Evita la contaminación por metales pesados.",
        ),
        ("Donar ropa o juguetes en buen estado", "Alarga su vida útil."),
        ("Usar pañales de tela", "Reducen residuos no biodegradables."),
        ("Comprar a granel", "Evita empaques innecesarios."),
        ("Reutilizar frascos y envases", "Dales una segunda vida como almacenamiento."),
        ("Imprimir solo lo necesario", "Usa papel reciclado y imprime a doble cara."),
        (
            "Elegir productos con empaques biodegradables",
            "Prioriza cartón, vidrio o bambú.",
        ),
        ("Reparar antes de tirar", "Arregla electrodomésticos, muebles o ropa."),
        ("Usar baterías recargables", "Disminuye residuos tóxicos."),
        (
            "Hacer manualidades con materiales reciclados",
            "Reutiliza cartón, botellas, etc.",
        ),
        (
            "Evitar productos desechables (cubiertos, platos)",
            "Prefiere opciones reutilizables.",
        ),
        ("Compostar café y té usado", "Son excelentes para el compost."),
        (
            "Reciclar aceite de cocina",
            "Llévalo a puntos de reciclaje (nunca al desagüe).",
        ),
        ("Usar servilletas de tela", "Sustituye las de papel."),
        ("Evitar recibos impresos", "Pide facturas digitales."),
        ("Compartir o alquilar herramientas poco usadas", "Reduce consumo y residuos."),
        (
            "Crear un sistema de reciclaje en casa",
            "Organiza contenedores por tipo de material.",
        ),
        ("Crear compostera casera", "Usa restos de comida para abono."),
        ("No imprimir boletos de transporte", "Usa versión digital."),
        ("Llevar bolsa propia al súper", "Evita bolsas plásticas de un solo uso."),
        ("Usar apps para donación de objetos", "Evita desechar artículos útiles."),
        ("Reutilizar papel de envoltura", "Para futuros regalos o manualidades."),
        ("Reducir el uso de servilletas", "Usa solo lo necesario."),
        ("Hacer compras conscientes", "Evita generar residuos por compras impulsivas."),
        (
            "Utilizar apps de recetas de aprovechamiento",
            "Evita tirar comida aprovechable.",
        ),
        ("Reparar ropa rota", "Coser en lugar de tirar."),
        ("Separar pilas usadas", "Llevar a centros de acopio."),
    ],
    "MOVILIDAD": [
        ("Caminar o usar bicicleta", "Para distancias cortas, evita emisiones."),
        ("Compartir coche (carpooling)", "Reduce tráfico y contaminación."),
        (
            "Usar transporte público",
            "Autobuses o trenes son más eficientes que coches individuales.",
        ),
        ("Conducir eficientemente", "Mantén velocidad constante y evita frenazos."),
        ("Teletrabajar cuando sea posible", "Reduce desplazamientos innecesarios."),
        (
            "Elegir vehículos eléctricos o híbridos",
            "Contaminan menos que los de combustión.",
        ),
        ("Planificar rutas", "Agrupa gestiones para evitar viajes repetidos."),
        ("Mantener neumáticos inflados", "Mejora la eficiencia del combustible."),
        ("Usar patinete eléctrico", "Alternativa sostenible para trayectos medios."),
        ("Evitar vuelos cortos", "Prefiere trenes para distancias menores a 500 km."),
        ("Viajar ligero", "Menos peso en el coche = menos consumo de combustible."),
        ("Apagar el motor en paradas largas", "Evita el ralentí innecesario."),
        ("Optar por trenes nocturnos", "Alternativa ecológica a los aviones."),
        (
            "Usar apps para compartir viajes",
            "Blablacar o similares reducen huella de carbono.",
        ),
        ("Caminar en lugar de usar ascensor", "Ahorra energía y mejora tu salud."),
        ("Promover ciclovías en tu comunidad", "Fomenta el transporte sostenible."),
        (
            "Evitar aceleraciones bruscas",
            "Conducir suavemente ahorra hasta un 20% de combustible.",
        ),
        ("Elegir hoteles con certificación ecológica", "Apoya al turismo sostenible."),
        ("Usar coches solo cuando sea indispensable", "Prioriza otras opciones."),
        (
            "Educar en movilidad sostenible",
            "Enseña a otros los beneficios del transporte verde.",
        ),
        ("Organizar carpool en el trabajo", "Coordina viajes con colegas."),
        ("Usar apps de rutas óptimas", "Evita tráfico y reduce emisiones."),
        (
            "Llevar bicicleta al trabajo",
            "Combina con transporte público si es necesario.",
        ),
        ("Mantener coche afinado", "Reduce emisiones contaminantes."),
        ("Caminar al mercado", "Evita uso del coche para distancias cortas."),
        (
            "Usar plataformas de movilidad compartida",
            "Alternativas sostenibles y económicas.",
        ),
        ("Adoptar rutina de caminatas diarias", "Beneficia tu salud y el planeta."),
        ("Evitar usar auto para recados cortos", "Agrupa salidas en un solo viaje."),
        ("Evitar acelerar al arrancar", "Arranque suave ahorra combustible."),
        ("Promover el ciclismo urbano", "Comparte experiencias y consejos en redes."),
    ],
    "CONSUMO": [
        ("Comprar local", "Reduce huella de carbono por transporte."),
        ("Evitar fast fashion", "Elige ropa duradera y de comercio justo."),
        ("Reducir consumo innecesario", "Pregúntate: ¿realmente lo necesito?"),
        ("Elegir productos de segunda mano", "Alarga la vida útil de objetos."),
        ("Usar botellas y tazas reutilizables", "Evita plásticos desechables."),
        ("Comprar alimentos de temporada", "Son más baratos y sostenibles."),
        (
            "Reducir consumo de carne",
            "La producción animal tiene alta huella ecológica.",
        ),
        ("Evitar productos con microplásticos", "Dañan los ecosistemas acuáticos."),
        (
            "Priorizar materiales naturales",
            "Algodón orgánico, madera certificada, etc.",
        ),
        ("Reparar antes de comprar nuevo", "Extiende la vida de tus pertenencias."),
        ("Usar buscadores ecológicos (Ecosia)", "Plantan árboles con tus búsquedas."),
        (
            "Evitar el sobreenvasado",
            "Rechaza productos con múltiples capas de plástico.",
        ),
        (
            "Compartir suscripciones (Netflix, revistas)",
            "Reduce la producción de recursos.",
        ),
        ("Comprar a granel con tus propios recipientes", "Cero residuos de empaques."),
        ("Elegir cosmética sólida (jabón, champú)", "No genera envases plásticos."),
        ("Donar libros usados", "Promueve la reutilización."),
        ("Usar energía verde en casa", "Contrata compañías con fuentes renovables."),
        ("Evitar compras impulsivas", "Haz listas y espera 24h antes de comprar."),
        (
            "Invertir en calidad sobre cantidad",
            "Mejor 1 producto duradero que 5 desechables.",
        ),
        (
            "Educar sobre consumo responsable",
            "Comparte información con amigos/familia.",
        ),
        ("Comprar solo con lista", "Evita compras impulsivas innecesarias."),
        ("Leer etiquetas de productos", "Prefiere los de origen sostenible."),
        ("Usar bolsas reutilizables para frutas", "Evita bolsas pequeñas desechables."),
        (
            "Hacer trueque con conocidos",
            "Intercambia cosas en lugar de comprar nuevas.",
        ),
        ("Probar dieta vegetariana un día a la semana", "Reduce impacto ambiental."),
        ("Revisar inventario antes de comprar", "Evita duplicar productos."),
        ("Cancelar suscripciones innecesarias", "Reduce consumo digital."),
        ("Preferir electrodomésticos duraderos", "Menos reemplazos, menos consumo."),
        ("Revisar reseñas antes de comprar", "Asegura calidad y evita compras malas."),
        ("Elegir tiendas con prácticas sostenibles", "Apoya negocios conscientes."),
    ],
}
